### ISSUE TITLE
`addPromoCode` return type is incorrect

### ISSUE THREAD

**Issue by msichterman** [SplitPass/mindbody-api#8]
The `Site.addPromoCode` return type is incorrect. It is `Promise<ProspectStages>`, when it should be `Promise<PromoCode>`

## Expected
```ts
async function addPromoCode(
  args: RequestArgsPost<AddPromoCodePayload>,
): Promise<PromoCode> {
  return await MINDBODY.post('/site/addpromocode', args);
}
```

## Actual (Current Implementation)
```ts
async function addPromoCode(
  args: RequestArgsPost<AddPromoCodePayload>,
): Promise<ProspectStages> {
  return await MINDBODY.post('/site/addpromocode', args);
}
```

Link to code: https://github.com/SplitPass/mindbody-api/blob/bce867971dda1bc4dffe24bfd035d59d8462804e/src/mindbody/Site.ts#L304-L308

**Comment by kylesurowiec** [comment]
Thanks @msichterman. I'll try and get this fixed this evening. Feel free to PR if you need it before then

**Comment by msichterman** [comment]
Thanks!¨̮ @kylesurowiec
